config/routes.rb
Rails.application.routes.draw do
  root to: 'bookmarks#index'

  resources :bookmarks, only: %i[index new create edit update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :site
  has_and_belongs_to_many :tags

  validates :site, :url, :title, presence: true

  scope :search, ->(q) {
    joins(%Q{
      JOIN (
        SELECT
          bookmarks.id,

          (
            to_tsvector(bookmarks.title) ||
            to_tsvector(bookmarks.url) ||
            to_tsvector(COALESCE(bookmarks.short_url, '')) ||
            to_tsvector(
              COALESCE(string_agg(tags.name, ' '), '')
            )
          )  as document
        FROM bookmarks
        LEFT JOIN bookmarks_tags ON bookmarks_tags.bookmark_id = bookmarks.id
        LEFT JOIN tags ON tags.id = bookmarks_tags.tag_id
        GROUP BY bookmarks.id
      ) terms ON terms.id = bookmarks.id
    }).where('terms.document @@ ?', q).select('DISTINCT bookmarks.*')
  }

  def inline_tags
    tags.order(:name).map(&:name).join(',')
  end

  def inline_tags=(tags)
    self.tags = tags.split(',').map do |name|
      Tag.find_or_create_by(name: name)
    end
  end
end

app/models/site.rb
class Site < ApplicationRecord
  validates :url, presence: true, uniqueness: true
end

app/models/tag.rb
class Tag < ApplicationRecord
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def index
    @bookmarks = Bookmark.search(params[:q]).order(:created_at)
  end

  def new
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = BookmarkCreator.new(bookmark_params).create

    if @bookmark.persisted?
      redirect_to :bookmarks
    else
      render :new
    end
  end

  def edit
    @bookmark = Bookmark.find(params[:id])
  end

  def update
    @bookmark = BookmarkUpdater.new(
      Bookmark.find(params[:id]),
      bookmark_params
    ).update

    if @bookmark.valid?
      redirect_to :bookmarks
    else
      render :edit
    end
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:title, :url, :short_url, :inline_tags)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookmarks/_form.html.erb
<% if @bookmark.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@bookmark.errors.count, "error") %> prohibited this bookmark from being saved:</h2>

    <ul>
      <% @bookmark.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_for @bookmark do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="row">
    <div class="col-md-6">
      <div class="form-group">
        <%= f.label :url %>
        <%= f.text_field :url, class: 'form-control' %>
      </div>
    </div>

    <div class="col-md-6">
      <div class="form-group">
        <%= f.label :short_url %>
        <%= f.text_field :short_url, class: 'form-control' %>
      </div>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :inline_tags, 'Tags' %>
    <%= f.text_field :inline_tags, class: 'form-control' %>
    <span class="help-text">each tag must be comma separated</span>
  </div>

  <%= f.submit 'Save', class: 'btn btn-primary' %>
  <%= link_to 'Cancel', [:bookmarks], class: 'btn btn-default' %>
<% end %>

app/views/bookmarks/edit.html.erb
<h1>Editing <%= @bookmark.title %></h1>

<%= render 'form' %>

app/views/bookmarks/index.html.erb
<h1>My bookmarks</h1>

<%= link_to 'New bookmark', [:new, :bookmark], class: 'btn btn-primary' %>

<br><br>
<%= form_tag bookmarks_path, method: :get, class: 'form-inline' do %>
  <div class='form-group'>
    <%= text_field_tag :q, params[:q], placeholder: 'Search bookmarks', class: 'form-control' %>
  </div>

  <%= submit_tag 'Search', class: 'btn btn-info' %>
<% end %>

<table class="table table-striped">
  <thead>
    <tr>
      <th>#</th>
      <th>Title</th>
      <th>Tags</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
    <% if @bookmarks.empty? %>
      <tr>
        <td colspan="4">No bookmarks found</td>
      </tr>
    <% else %>
      <% @bookmarks.each do |bookmark| %>
        <tr>
          <td><%= bookmark.id %></td>
          <td><%= bookmark.title %></td>
          <td><%= bookmark.inline_tags %></td>
          <td>
            <%= link_to 'Edit', [:edit, bookmark], class: 'btn btn-sm btn-success' %>
            <%= link_to 'Access', bookmark.url, target: 'blank', class: 'btn btn-sm btn-default' %>
          </td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

app/views/bookmarks/new.html.erb
<h1>New bookmark</h1>

<%= render 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookmarks</title>
    <%= csrf_meta_tags %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all' %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>

    <%= javascript_include_tag 'application' %>
  </body>
</html>